# Generated by Django 4.2 on 2023-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=255, verbose_name='County name')),
                ('county_photo', models.ImageField(upload_to='images/core/county_photo')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'ordering': ['county_name'],
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_title', models.CharField(max_length=255, verbose_name='Cover title')),
                ('cover_text', models.TextField(max_length=255, verbose_name='Cover text')),
                ('cover_photo', models.ImageField(upload_to='images/core/cover_photo', verbose_name='Cover photo')),
            ],
            options={
                'verbose_name': 'Manage cover',
            },
        ),
    ]
