# Generated by Django 4.2 on 2023-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(upload_to='static/images/cover_photo')),
            ],
            options={
                'verbose_name': 'Cover Photo',
                'verbose_name_plural': 'Cover Photos',
            },
        ),
    ]
