# Generated by Django 4.2 on 2023-04-18 16:41

from django.db import migrations, models
import django.db.models.deletion
import hotels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255, verbose_name='Hotel name')),
                ('hotel_city', models.CharField(max_length=255, verbose_name='Hotel city')),
                ('hotel_street', models.CharField(max_length=255, verbose_name='Hotel street')),
                ('hotel_zip_code', models.CharField(max_length=10, verbose_name='Hotel Zip code')),
                ('hotel_description', models.TextField(verbose_name='Hotel overview')),
                ('hotel_has_free_wifi', models.BooleanField(default=False, verbose_name='Free wifi')),
                ('hotel_has_air_conditioning', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('hotel_has_parking_available', models.BooleanField(default=False, verbose_name='Parking available')),
                ('hotel_has_business_services', models.BooleanField(default=False, verbose_name='Business Services')),
                ('hotel_has_swimming_pool', models.BooleanField(default=False, verbose_name='Swimming pool')),
                ('hotel_has_top_rated_in_area', models.BooleanField(default=False, verbose_name='Top rated in area')),
                ('hotel_has_flat_screen_tv', models.BooleanField(default=False, verbose_name='Flat-screen TV')),
                ('hotel_has_24_hour_front_desk', models.BooleanField(default=False, verbose_name='24-hour front desk')),
                ('hotel_has_non_smoking_rooms', models.BooleanField(default=False, verbose_name='Non-smoking rooms')),
                ('hotel_has_fitness_center', models.BooleanField(default=False, verbose_name='Fitness center')),
                ('hotel_has_room_service', models.BooleanField(default=False, verbose_name='Room service')),
                ('hotel_has_restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
                ('hotel_is_pet_friendly', models.BooleanField(default=False, verbose_name='Pet friendly')),
                ('hotel_has_facilities_for_disabled_guests', models.BooleanField(default=False, verbose_name='Facilities for disabled guests')),
                ('hotel_has_family_rooms', models.BooleanField(default=False, verbose_name='Family rooms')),
                ('hotel_has_spa', models.BooleanField(default=False, verbose_name='Spa')),
                ('hotel_has_airport_shuttle', models.BooleanField(default=False, verbose_name='Airport shuttle')),
                ('hotel_has_electric_vehicle_charging_station', models.BooleanField(default=False, verbose_name='Electric vehicle charging station')),
                ('hotel_cover_photo', models.ImageField(upload_to=hotels.models.cover_hotel_photo_path, verbose_name='Hotel cover photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('hotel_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.countries', verbose_name='Hotel country')),
            ],
            options={
                'verbose_name': 'Hotels',
                'verbose_name_plural': 'Hotels',
                'ordering': ['hotel_name', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='HotelsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_images', to='hotels.hotels')),
            ],
        ),
    ]
