# Generated by Django 4.2 on 2023-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
