# Generated by Django 4.2 on 2023-05-11 17:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotelsimage_options_hotels_hotel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queen_bed_quantity', models.PositiveIntegerField(default=0)),
                ('sofa_bed_quantity', models.PositiveIntegerField(default=0)),
                ('king_bed_quantity', models.PositiveIntegerField(default=0)),
                ('twin_bed_quantity', models.PositiveIntegerField(default=0)),
                ('full_bed_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomdiscount',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='bed_types',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_discount',
            field=models.IntegerField(blank=True, default=None, help_text='Discount percentage (optional) in %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='special_discount',
            field=models.CharField(blank=True, default=None, help_text='Special discount (optional) in text', max_length=50),
        ),
        migrations.DeleteModel(
            name='BedType',
        ),
        migrations.DeleteModel(
            name='RoomDiscount',
        ),
        migrations.AddField(
            model_name='roomtypebed',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
    ]
