# Generated by Django 4.2 on 2023-04-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roomtype_room_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.PositiveIntegerField(help_text='Number of beds in the room')),
                ('bed_types', models.CharField(choices=[('queen', 'Queen bed'), ('sofa', 'Sofa bed'), ('king', 'King bed'), ('twin', 'Twin bed'), ('full', 'Full bed')], help_text='Types of beds in the room (comma-separated)', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='size',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='sleeps',
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, help_text='Is the room currently available?'),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(default=None, help_text='Notes for the room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=None, help_text='Room number', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default=None, help_text='Description of the room type'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Price per night of the room type', max_digits=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(help_text='Name of the room type', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_type', 'room_number')},
        ),
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_types',
            field=models.ManyToManyField(help_text='Types and quantities of beds in the room', to='hotels.bedtype'),
        ),
    ]
