# Generated by Django 4.2 on 2023-04-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_bedtype_alter_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='hotels',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='hotels.hotels'),
        ),
    ]
