# Generated by Django 4.2 on 2023-05-14 10:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomtypebed_remove_roomdiscount_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hotel', chained_model_field='hotels', on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
    ]
