# Generated by Django 4.2 on 2023-05-31 15:51

from django.db import migrations, models
import django.db.models.deletion
import hotels.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_room_hotel_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=None, help_text='Room number', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hotel', chained_model_field='hotels', default=None, help_text='Room type', on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.hotel_room_photos_path),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.hotel_room_photos_path),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.hotel_room_photos_path),
        ),
    ]
