# Generated by Django 4.2 on 2023-06-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_room_max_guests_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotel_rating',
            new_name='user_rating',
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_star_rating',
            field=models.PositiveIntegerField(choices=[(0, '0 Stars'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0, verbose_name='Hotel star rating'),
        ),
    ]
