# Generated by Django 4.2 on 2023-06-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_rename_hotel_rating_hotels_user_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelfacilities',
            old_name='hotel_is_pet_friendly',
            new_name='hotel_has_pet_friendly',
        ),
    ]
