# Generated by Django 4.2 on 2023-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotels_is_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='amount_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='recommended_score',
            field=models.FloatField(default=0),
        ),
    ]
