# Generated by Django 4.2 on 2023-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotels_amount_of_reviews_hotels_recommended_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
