# Generated by Django 4.2 on 2023-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotels_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
