# Generated by Django 4.2 on 2023-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_hotels_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
