# Generated by Django 4.2 on 2023-06-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_hotels_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='area',
            field=models.PositiveIntegerField(default=0, help_text='Room area'),
        ),
    ]
