# Generated by Django 4.2 on 2023-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_alter_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per night of the room', max_digits=8),
        ),
    ]
