# Generated by Django 4.2 on 2023-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Title')),
                ('blog_text', models.TextField(verbose_name='Text')),
                ('blog_photo', models.ImageField(upload_to='static/images/blog')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is publised')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['blog_title', 'time_create'],
            },
        ),
    ]
