# Generated by Django 4.2 on 2023-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_photo',
            field=models.ImageField(upload_to='images/blogs'),
        ),
    ]
