# Generated by Django 4.2 on 2023-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_list',
            name='hotel_country',
            field=models.CharField(max_length=255, verbose_name='Hotel country'),
        ),
    ]
