# Generated by Django 4.2 on 2023-04-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hotel_list', '0002_alter_hotel_list_hotel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_list',
            name='hotel_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.countries'),
        ),
    ]
