# Generated by Django 4.2 on 2023-05-02 12:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_path),
        ),
    ]
