# Generated by Django 4.2 on 2023-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_photo',
            field=models.ImageField(upload_to='static/images/blog'),
        ),
    ]
